server:
  port: 8080
spring:
  application:
    name: microserv-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: microserv-maintenance
            uri: lb://microserv-maintenance
            predicates:
              - Path=/api/maintenance/**
          - id: microserv-scooter
            uri: lb://microserv-scooter
            predicates:
              - Path=/api/scooter/**
          - id: microserv-billing
            uri: lb://microserv-billing
            predicates:
              - Path=/api/billing/**
          - id: microserv-fee
            uri: lb://microserv-billing
            predicates:
              - Path=/api/fee/**
          - id: microserv-parking
            uri: lb://microserv-parking
            predicates:
              - Path=/api/parking/**
          - id: microserv-travel
            uri: lb://microserv-travel
            predicates:
              - Path=/api/travel/**
          - id: microserv-user
            uri: lb://microserv-user-account
            predicates:
              - Path=/api/user/**
          - id: microserv-account
            uri: lb://microserv-user-account
            predicates:
              - Path=/api/account/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: microserv-gateway
        url: /v3/api-docs
      - name: microserv-maintenance
        url: /api/maintenance/v3/api-docs
      - name: microserv-parking
        url: /api/parking/v3/api-docs
      - name: microserv-scooter
        url: /api/scooter/v3/api-docs
      - name: microserv-travel
        url: /api/travel/v3/api-docs
      - name: microserv-user
        url: /api/user/v3/api-docs
      - name: microserv-acount
        url: /api/user/v3/api-docs
      - name: microserv-billing
        url: /api/billing/v3/api-docs
      - name: microserv-fee
        url: /api/fee/v3/api-docs
