version: '3.8'
services:
  db_Maintenance:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_Maintenance
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"