version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: MaintenanceDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"