version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Integrador4
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"