version: '3.8'
services:
  db_Billing:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_Billing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"